esmero/format_strawberryfield

- format_strawberryfield.libraries.yml
- js/iiif-pannellum_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
This pull adds [Pannellum](https://pannellum.org) to the Formatter options.
- Pannellum as a Library and a custom JS to deal with our formatter. Includes Hotspots (I just did more than expected)
- A Strawberry field formatter that can read images and hotspots
We now have already a few formatters and things start to look good. But: we need to consolidate common functionality in a single class and extend it only for the particularities. Not happy with adding duplicated code just per se. Media, Single Image and Book reader share quite some code.
> Pannellum Panorama Viewer

- js/iiif-iabookreader_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
Maybe we need additional checks or code cleaning, while this works following these steps:
- add a display (i.e. Digital Object with Book Reader and external manifest) and set media source Strawberryfield JSON Key with a Manifest URL and Json key (i.e. iiifmanifest)
- add a digital object with a minimal Json with a key "iiifmanifest" with manifest URL value (i.e. http://www.byterfly.eu/islandora_iiif/librib:927474/manifest) and assign previous created display.
@DiegoPino feel free to wait for merging, probably I'll make more check tomorrow, as you want
> First working External manifest

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.libraries.yml
- js/leaflet_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
See #61
First naive attempt on Mapping. What does this formatter provide?
3 Choices for Geographic data, all in super-duper-GeoJSON.
- A Metadata Exposed endpoint (copying at the end here so people can test)
- Choice of a Field with a list of nodes (can be `memberof`, `closeto`, you decide)
- one or more External URLS (or internals, but actual absolute ones) pointing to GEOJSON. Because of the nature of internet and the fact that we get them via AJAX CORS needs to be working and allowing your Archipelago to fetch the JSON. If not we could enable JSONP (new word! google it!)
- A filter to decide if showing a map or not is needed. This is new but needed. Since maps always render the tiles first, an ADO without geographic data would end displaying empty maps. You can setup a conditional for …
> Issue-61: Let's travel around the globe

- composer.json
- format_strawberryfield.info.yml
- format_strawberryfield.libraries.yml
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
- templates/format-strawberryfield-pdfs.html.twig
Yes, #75 but really to RC-3 and also doing some last deprecation (a single one!) replacement for Drupal 9. This also includes matching latest dependencies with newer version as recently tested. Check!
> ISSUE-75: Update mirador and D9 Dependencies update

- config/schema/format_strawberryfield.schema.yml
- js/plugin.iiif-iabookreader_strawberry.js
Last minute fixes for 8.x-1.0-beta3 Release. New WARC formatter was missing proper Schema properties. Fixed
Also so why people like YAML?  … Same reason they like Python? Indentation feels like a semantic moral failure in programming languages. Perl ... o Perl how i miss you..
> 8.x 1.0-beta3RC: House keeping schema

- composer.json
- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.info.yml
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- format_strawberryfield.routing.yml
- js/iiif-pannellum_strawberry.js
- js/mirador_strawberry.js
- js/plugin.iiif-iabookreader_strawberry.js
- src/Controller/JsWorkerController.php
- src/Entity/MetadataDisplayEntity.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
- templates/format-strawberryfield-pdfs.html.twig
Release duties, bring master into code parity with 8.x-1.0-beta3
> merge 8.x-1.0-beta3 into master

- src/Controller/MetadataExposeDisplayController.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
See #96 
No more clearing the cache when your twig template changes? Is that true Mr P-i-n-o? @alliomeria look what i did.
Also falling asleep...
> ISSUE-96: Look Friend! WE got a Twig Context alter hook AND some cache tags

- composer.json
- js/iiif-iabookreader_strawberry.js
- js/plugin.iiif-iabookreader_strawberry.js
- js/uv_strawberry.js
First pass. 1UP pages work well. 2UP not yet, but probably it is not my fault. Will merge and then continue.
This also removes a dependency we never had "drupal/webform_views"
Also a stub UV JS. But we need to deploy UV locally so I need a drush script still for that. Long way to go
> Issue 105: OCR compat for IAB and remove old dependencies for D9 

- js/iiif-iabookreader_strawberry.js
@DiegoPino I found this was broken after last PR, this patch fix it, please check if ok also for you. I added a your function at the end because not available in this js file, I think could be optimized.
> Fix broken IAB Zoom on PDF source

- js/iiif-iabookreader_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
> ISSUE-118: Adds a way to hide the search bar in the paged formatter if the document is not processed via ocr. 

- src/Plugin/EntityReferenceSelection/NodeBearingStrawberryfieldSelection.php
See #157 
Single liner, no more warnings during Entity Autocomplete.
> ISSUE-157: Fix D9's new thing

- js/plugin.iiif-iabookreader_strawberry.js
This is very experimental code to try to work out/demonstrate a proof of concept of using the IIIF Presentation Manifest API 3.0 template to display a PDF-based book in the IA Bookreader. Once that's worked out, then my plan is to work out how to display a creative work series in the IA Bookreader.
> ISSUE #184: Enable Creative Work Series and PDF to be displayed in IABookReader using IIIF Presentation API 3.0 Manifest

- src/TwigExtension.php
> ISSUE-199: EDTF Humanizer Twig Extension

- js/plugin.iiif-iabookreader_strawberry.js
See #210, not a big issue. Fixed.
> ISSUE-210: Fix IIIFV3 v/s V2.1 regression on Bookreader

- composer.json
Resolves #227. Updates to archipelago-deployment and archipelago-deployment-live lock files to follow.
> ISSUE-227: Add citeproc-php to composer.json

- src/Element/EntityAutocompleteUUID.php
This is a stupid Views issue, not us. When loading a formatter for a Field in a Views that uses the entity UUID autocompleted we build (because you don't want to reference IDs, those change people), the Views opens an Ajax Windows that calls the validation of the Settings form before even displaying. At that moment the $value is NULL and you can't load an entity from storage with a NULL value. This small checks on nulls/elseif deals with it.  Also multiple entities should work now (but i have no use for that right now) Only issue is it will actually mark the field as "incomplete" but i don't see a way around this at all bc validation should not be called on Form render. Stupid views.
> ISSUE-224: Fix UUID Autocomplete validator when using Ajax (Views)

- src/CiteProc/Render.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Begins to resolve #232 by checking for bibliography nodes in each style for the formatter form. More commits to come.
> ISSUE-232: citeproc-php error for style(s) that can't render with given data

- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Resolves #236 for branch 1.0.0.
The check for NULL was already there. Just needed to move the rest of the metadata display entity rendering into the try block.
> ISSUE-236: Citation Formatter check for null

- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Resolves #241 for the 1.1.0 branch.
> ISSUE-241: Citation Formatter settings undefined variables

- css/iabookreader.css
- format_strawberryfield.libraries.yml
- js/plugin.iiif-iabookreader_strawberry.js
Begins to resolve #262. CSS to come.
> ISSUE-262: Internet Archive Bookreader mobile menu is broken

- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
My bad. This is better code and is consistent with Video
> ISSUE-269b:Fix height on VTTs/Audio

- src/Element/EntityAutocompleteUUID.php
> ISSUE-300: Make UUID Entity Reference act on String based defaults (UUID and Arrays of UUIDs)

- src/Entity/MetadataDisplayEntity.php
- src/Form/MetadataDisplayForm.php
- src/MetadataDisplayInterface.php
> ISSUE-289: Misreported unused JSON keys for multilevel keys in Metadata Display preview

- modules/format_strawberryfield_facets/src/Plugin/facets/processor/DateRangeProcessor.php
> ISSUE-308: Fix null coalescing operator's order at DateRangeProcessor.php

- src/Form/MetadataDisplayForm.php
> ISSUE-310: Show Pretty printed JSON when rendering using native/validated option

- src/Form/MetadataDisplayForm.php
Gosh. Made a stupid/too quick typo. Fixing now see #310
> ISSUE-310: lazy me, Update MetadataDisplayForm.php

- src/Entity/MetadataDisplayEntity.php
- src/Form/MetadataDisplayForm.php
Resolves #350, #318, and #306.
@DiegoPino I believe this rearrangement bypasses the edge case, but I wasn't able to reproduce those errors so not 100% sure. Even if it does cover those cases, I think this could definitely use further simplification. I'd be glad to open another issue to keep improving on that front later if this looks ok.
> ISSUE-350: Refactor Metadata Preview used variables functionality

- src/Form/MetadataDisplayForm.php
> ISSUE-358: Metadata Display Preview Codemirror output visually inconsistent

- README.md
See esmero/archipelago-documentation#179.
> ISSUE-371: Remove name from docs

- format_strawberryfield.libraries.yml
- js/leaflet_strawberry.js
See #365 
Nothing breaks, just bug fixes and better event support. Also normal patch/fix/upgrade economy
> ISSUE-365:Upgrade leaflet to latest stable

- src/EmbargoResolver.php
> ISSUE-377: catch up on multiple IPs for embargo bypass for 1.2.0 (back port)

- format_strawberryfield.post_update.php
- src/Entity/MetadataDisplayEntity.php
See #182 
Deals with https://www.drupal.org/project/drupal/issues/3317361
Requires Drupal 10.1
And this to be pulled and merged (which can be merged on D10) 
https://github.com/esmero/strawberryfield/issues/291
> ISSUE-182: Makes Metadata Display Entities revision able

- composer.json
- format_strawberryfield.info.yml
- modules/format_strawberryfield_facets/config/schema/format_strawberryfield_facets.schema.yml
- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/js/facets-views-ajax.js
- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
See #404 but for 1.3.0. This will also allow us to ship a reliable for Drupal 10 advance search experience on archipelago deployment
@alliomeria 👁️  (thx for your work on those settings)
> ISSUE-404 for 1.3.0: Advance search fixes that are also needed on 1.3.0

- .idea/.gitignore
- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
> ISSUE-408: Adds multi value check for required, validate count on non empties

- format_strawberryfield.libraries.yml
- js/iiif-iabookreader_strawberry.js
- js/plugin.iiif-iabookreader_strawberry.js
- modules/format_strawberryfield_views/js/sbf-views-ajax-dynamic.js
- modules/format_strawberryfield_views/src/Plugin/views/display_extender/StrawberryAjaxInteractions.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
> ISSUE-430: Various AJAX/Interactions and Views fixes

- src/TwigExtension.php
- Added entity query access check in TwigExtension::entityIdsByLabel
> Issue-447: missing accessCheck in TwigExtension::entityIdsByLabel

- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
> ISSUE-474: BEF Advanced Search & Modal Exposed Form Block improvements

- modules/format_strawberryfield_views/js/modal-exposed-form-interactions.js
- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
> ISSUE-476: Advanced Search and Modal Exposed Form 

- src/Plugin/Condition/AdoFlavors.php
See #501 
Simple. Well written. perfect British (with fancy accent too). Does the job and works,
Looks like this
depends on https://github.com/esmero/strawberryfield/pull/351
> ISSUE-501: Adds the Flavour Condition for Blocks

- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
See #505 . This is a backwards patch to fix leaking ajax_page_state. This is already fixed in 1.5.0
> ISSUE-505: Fix leaking ajax_page_state for Drupal 10.2.x

- modules/format_strawberryfield_facets/src/Controller/SbfFacetBlockAjaxController.php
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Controller/ViewsExposedFormModalBlockAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
Includes some other smaller improvements on our overridden Ajax Logic
> Issue 503: Ajax Block/better exposed fields interaction on 7.0.6+

- js/iiif-openseadragon_strawberry.js
> ISSUE-518: Only spread if spreadable (or butter)
