- css/iabookreader.css
- js/iiif-iabookreader_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
We have to override .BookReader.fullscreen to add !important.
Using @DiegoPino code, max width/height settings applyed to BookReader div
> Fix BookReader fullscreen

- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
This pull implements @giancarlobi (👏 ) code to allow Page sorting for the IIIF manifest generated using a Metadata Display (Twig template). It assumes we will have a "sequence" key for each as:image item (each one is a JSON object) but will work even when the key is missing.
This should work out of the box for the book reader using the existing IIIF 3.0 Manifest Metadata Display. But if you feel you have the time to experiment a bit more you can add a "sequence" key with an Integer value to any  (or all) of the JSON Objects inside the `as:image` key. Something like
```JSON
"as:image": {
"s3:\/\/7a4\/1b3d19e9764ffee26440de032d26d66e1a90def9-en-image-1b3d19e9764ffee26440de032d26d66e1a90def9.jpg": {
"url": "s3:\/\/7a4\/1b3d19e9764ffee26440de032d26d66e1a90def9-en-image-1b3d19e9764ffee26440de03 …
```
> Allow for Page sorting using a json key

- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
This pull moves some logic into an existing conditional: can we retrieve the size of an image via cantaloupe? If not, stop processing. Previously, if you had a badly set Formatter (because you are moving configurations around and your IIIF server IPs do not match!) or you are referencing an image that does not exist (because you are testing stuff) you will get some bad errors.
- If you reference a non existing image in your JSON or
- you have a badly set IIIF endpoint
And you are trying to display a thumbnail or a static image from Cantaloupe
You will see a notice about a wrong operand on line 289.
Apply this and thumbnail generation will simply be skipped.
@giancarlobi i will go an merge this one, because i need it on production. But please feel free to test and give me some feedback. …
> Fix static image processing on failure

- format_strawberryfield.routing.yml
- src/Entity/MetadataExposeConfigEntity.php
- src/Form/MetadataExposeConfigEntityDeleteForm.php
See #27 and #22 
Mostly my fault: i introduced some errors because i did this in piece with time lapses inbetween (busy person) and in too many attempts and left first attempt code around. This fixes:
- Deleting an Exposed Metadata Config Entity (Wrong class for the form)
- Better message when deleting
- Sorting by label when showing the list of entities.
- Removes the Regular expression matcher for the route and adds our new resource_type =  'ado' parameter to the actual endpoint so the https://github.com/esmero/strawberryfield/tree/ISSUE-47 can be used. Does not affect right now anything other than ID resolving versus UUID resolving
@giancarlobi can you check this? I actually did create/delete/recreate and delete a few times. I hope i got it right this time and thanks for reviewing my …
> ISSUE-22: Fix left overs from first  ISSUE-22 pull (Number 27)

- format_strawberryfield.routing.yml
- src/Controller/MetadataExposeDisplayController.php
- src/Entity/Controller/MetadataExposeConfigEntityListBuilder.php
- src/Form/MetadataExposeConfigEntityForm.php
Bug fixes and enhancements
See #27 and #22 and #31 
- This adds a better Collection Listing format for each Config Entity, 
- We also now (cool) show a demo/example link on the listing, so people can see/where/how each endpoint can be found. I like it!
- Makes sure `isActive()` is enforced in config but also on the Controller
- Adds also the Config Entity as a Cacheable dependency so changes like enable/disabling are visible immediately.
-  removes some wrong routing (no canonical for the config entity!). 
@giancarlobi this is all yours, please test if you can before merging. I feel i finally addressed everything. @marlo-longley if you want to look at this too!
> ISSUE-22: Fix Routing issues and Active/inactive, Gives the Config Entity some Love

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.links.menu.yml
- format_strawberryfield.module
- format_strawberryfield.routing.yml
- src/Form/ViewModeMappingSettingsForm.php
See #33 
This pull implements a generalized solution for triggering existing Drupal View Modes based on mapped settings between those and **existing** JSON types values indexed already in Solr.
High emphasis on:  **existing** JSON types values indexed already in Solr.
The logic is quite simple:
1. An Archipelago Settings Form Endpoint where you can select a pair of Types (select box populated from already ingested types) and a View Mode.
- The form allows to add more pairs without limiting (for now) having the same repeated (@TODO) a few times
- People can reorder how those mappings are evaluated. Useful for defining general types like "image" as defaults when not other more specific TYPE matches. Note: Image, e.g comes from a deeper JSON structure, so really anything that has a file of …
> ISSUE-33: JSON Type/ADO  to View Mode Mapping

- format_strawberryfield.module
When we have no mappings yet, the alter hook throws some errors. Make sure mappings, even when empty are always an array() . Thanks @mitchellkeaney for testing and catching this
With existing mapping all should work as before, with an empty config, no error should appear.
> ISSUE-33: Small fix for empty Viewmode mapping configs

- src/Form/ViewModeMappingSettingsForm.php
See #33 for context
After getting more feedback during a call on Friday i decided to address the fact that our "add" new mapping button for the ADO type to View Mode Form was on the bottom (unexpected) and not just right by the select boxes. This pull fixes that. It also changes the way we display the already selected View Modes and deals (sort of) with the fact that people could have deleted a view mode after we saved the mappings. If that happens, on load we replace the View Mode Label colum with a select box allow the Admin to fix its mistake. I also did some code rearranging (to avoid long lines, nothing really impressive there but adds some clutter to the pull, sorry!)
Fetch branches, switch to this, clear caches, check your form.
If you want to test the behavior on a broken View …
> ISSUE-33: make UI consistent

- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
Addresses #24 
Not much. Just markup and text/labels in the "Metadata using Twig" formatter to clarify the user experience, purpose of the form, autocomplete, and where users can find the list of templates elsewhere in Drupal.
Go to the "Manage Display" tab for Digital Objects. Select "Strawberry Field Custom Metadata Template" from Formatter dropdown to see new language.
> ISSUE-24: Enhance Strawberry Field Custom Metadata Template Settings Form

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- js/iiif-iabookreader_strawberry.js
- js/iiif-openseadragon_strawberry.js
- js/iiif-pannellum_strawberry.js
- js/jsm-model_strawberry.js
- src/MetadataExposeConfigEntityHtmlRouteProvider.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
see #20 
- New Pannellum JS version (2.5.4) only 22 days old!
- Tested Dynamically loading Libraries via Ajax via Ajax again. That was failing (of course, who does that) but know it, now it works. Short answer, Document context of JS does not exist when there is an in memory document. Who would have guessed.
- StrawberryPannellumFormatter now gets another setting. With that it can try to fetch a nested list of other Scenes and their hotspots, where each scene is a node id. Basically a Formatter that uses other Nodes and their Formatters. It gets render arrays from each Node using the same setting of the one you/me/someone is viewing (so smart...gosh...i wish i was me) and rebuilds a new render `array` with all the results. Pushed that data into a little bit modifed JS and BUM! You have a …
> ISSUE-20: Tour/Scene builder Multi panorama aware Formatter.

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.routing.yml
- src/Controller/IiifBinaryController.php
- src/Entity/MetadataExposeConfigEntity.php
See #38 
We expose now, for logged in users, a direct endpoint to temporary files (e.g uploaded during a Webform ingest/edit workflow). This is needed to allow other modules to show/preview files are not persisted yet and our IIIF server can not reach yet to serve.
This pull also deals with #37 (hopefully) because i'm running out of time to make multiple pulls for everything that requires my attention. Citing myself 
`"Pino, Diego ; mapping: boolean? That was a weird one!"`
> ISSUE-38: Add a Temp file route with IIIF pattern

- src/Controller/MetadataExposeDisplayController.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
See #40 
Sequence ordering of our as:media elements everywhere they are used in output/formatters.
This is based on @giancarlobi work on the `::orderPages` method. It just extends the same concept to every other formatter and Twig injecting process and moved methods to common classes.
@giancarlobi @marlo-longley
> ISSUE-40: Add Media ordering to All formatters that need it

- src/Controller/MetadataExposeDisplayController.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
See #41 and #40 
Pull #41 introduced a bug that escaped my sleepy radar and some other folks radar too. This fixes it.
Requires https://github.com/esmero/strawberryfield/pull/63 to be merged/testing.
basically moves sequence ordering to our JSON Helper class and makes it static. Also renames the constant to uppercase (good practice) and cleans `MetadataExposeDisplayController` from being dependant on a formatter base class, never ever a good idea in the first place.
@marlo-longley please test as soon as possible. This is quite annoying!
> ISSUE-40:Fixing media ordering

- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
See #44 (First issue).
The default media entity ID was wrong (long time so). This unsets a default and also does a quick check on an existing entity before trying to set a label in the summary
@marlo-longley ping
> ISSUE-44 :Fix wrong Metadata Display ID default and check for entity before getting label

- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
Missed an edge (not so edge really) test case i was not handling correctly. If no JSON KEY for a node list exists and/or its empty, we try to load the entities anyway but` $cleannodelist`.list variable is not even initialised. Silly. Fix is simple
Just moves NODE loading into the IF jsonkey exists and initialize $cleannodelist. This deals with empty keys and non existing keys.
> ISSUE-49: Small fix for IIIF entities generated from a node list

- src/Controller/MetadataExposeDisplayController.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
See #52 
Just fixes and consistent behavior on setting/getting/adding to Twig template contexts.
Basically. We don't want saved trailing slashes, we never add them when pushing to Twig templates as Context variables. We add them back there if needed.
> ISSUE-52: normalize IIIF Server URLs

- config/schema/format_strawberryfield.schema.yml
This pull fixes mistakes I produced in #56 
Remove extra mirador settings under metadata_formatter
Fix indentation for mirador_formatter mapping
I was able to address the problem of mirador and metadata formatter settings being saved to other formatters by going deeper into the form, and re-saving the formatter options, as well as the overall Manage Display form for a certain View Mode.
> ISSUE-54: Schema fixes

- config/schema/format_strawberryfield.schema.yml
See #55 and #54 
So pull #19 introduced a lot of regression. Errors where not noticable since all our Archipelagos had already saved settings but the schema committed was not even visible, the naming convention matched nothing. I can't list all the errors, this was just too much.
This pull does the following:
- Normalizes back the names and fills the gap of missing formatter setting schemas, removes value? assignment when this is just a schema and also non-native types (seems like URL does not even exists?)
- [Uses a wild card](https://github.com/esmero/format_strawberryfield/commit/08718694f3d62721af2f3c0d8e378895288fc27f) to escape this non-sense  from drupal/ds module and solves #55 
```YAML
label: 'The field name'
fields:
type: sequence
label: 'The Display Suite field plugins' …
```
> ISSUE-54: Fix for good the ds.field schema issue related to formatters 

- config/schema/format_strawberryfield.schema.yml
- css/sbfutils.css
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- js/iiif-iabookreader_strawberry.js
- js/iiif-openseadragon_strawberry.js
- js/iiif-pannellum_strawberry.js
- js/jsm-model_strawberry.js
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
See #59 
All(well almost) formatters now support '0' width option to be used as a stub for 100% width.
The others, like some formatters that depend on Canvases (which need to have a fixed pixel size)e.g 3D one have an extra sizing functionality via JS that contracts the given canvas size in pixel to whatever is smaller (screen smaller than fixed with? We shrink to screen and redraw. Awesome!).
Also, other Formatters that totally need to have control over aspect ratio like PDF and Video allow to set '0' to force an `auto` height on a given `fixed` width. Great for avoiding squeezed video and PDFs like from 1997 when i was alive...and coding..
So JS improvements, like a `CSS` based preloader for our `3D Viewer` (who wants to wait looking at a white screen for a 3D skull of 10 Mbytes to …
> ISSUE-59: Allow 100% with for all formatters and some ++candy

- config/schema/format_strawberryfield.schema.yml
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
See #54 
Ok people, this finally solves all the Schema issues we had on this module. I found some issues left i'm tackling here. Status report now looks almost clear. Can not be 100% clear because some core issues i found (like if a Solr Data Source has not Display Mode it can not save its settings. Our SBF Flavour has no Display mode enabled yet, so i won't fix that). Also Views has Core issues with some missing schema definitions and finally our webform Handler id needs to be renamed. I won't touch that until beta3.
Also. Since i was here and there, i added a new option for the Simple Image Formatter. Now we can link to the node via the Thumbnail.  Quite useful, basic but was not present anywhere in core. Good. 
Also did some cleanup. All works! Now will make the huge settings commit to …
> Issue-54: Finally schemas are fixed and we have linked Thumbnails

- js/mirador_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
See #64 
A tiny bug fix, Mirador Viewer Formatter and Map one had the same HTML id being generated, blocking right JS attachment which is based on a selector passed via a data property. This fixes the issue. Since i was there i also removed the `JQuery` width setting for Mirador which was translating 100% to a fixed with, making variable with (specially when rescaling the window) impossible. I was not even aware of this. This gets merged in Beta2. And now moving forward with Beta3
> ISSUE-64: Fix duplicated HTML id/ Mirador and Map

- js/plugin.iiif-iabookreader_strawberry.js
See #71 
We use non standard IIIF extensions to be able to parse PDF pages from a single File as individual images. But in the IABookreader IIIF plugin we use the `service @id` of each image resource to build a full size image URL on the fly, to allow larger than desired Image sizes and zoom. NOTE: not sure that is really a good idea, we used the code IABookreader had for that and now looking this back in time it feels wrong.
In any case, by using the service URI we dismiss any argument, like `?page=1` that could be passed, which includes also video frame times, etc. This pull changes that by parsing out of the Image ID any arguments that could be passed and appending them to the final Image ID (URL) that is being built. This, in case of the absence of a `Service` and its `@id` we also …
> ISSUE-71: Make IABookreader aware of arguments in Image/Service @ids.

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- js/iiif-pannellum_strawberry.js
- src/Entity/MetadataDisplayEntity.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
See #78 
This pull will also solve a few other tiny things, like adding/pushing other fun things into the twig templates (hey, hey!) and wait for it... 2 more options for the static image formatter (nice one that we can use for thumbnails and such)..
- No image? Nothing to see? Choose a FONT! yep. a mapping per type: For now a static set using Fontawesome, but i expect this to have its own Config Form (who said me?)
- No image but part of another object? Or child of another one? or the opposite? Dad? Yes. Get your images from your neighbors' front yard and reuse. Plan here is to make that very action compatible, method for other stuff. Like 'compounding' and ACL inheritance. But that comes later...
> ISSUE-78: Metadata can now rule over display

- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- format_strawberryfield.routing.yml
- src/Controller/JsWorkerController.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
See #80 
You will see a few JS alerts but those are harmless. Related to how the web replay JS library tries multiple sources for its ui.js library. This adds a new formatter (proof of concept, can be way better and will be) 
`Strawberry Warc Formatter using replay.web Embedded player` with simple settings for now
JSON Source Key for WARCS (use as:document please), Width, Height and an extra one for remote URLs.
`@TODO:` add extra settings to hide nav bar via "embed=replay" and "url="
The rest is what we do, load some JS, iterate over some stuff, do some checks and render some HTML.
A note. I figured out that the issue with the height of the element/iframe is the fact that is not automatically seen as of type block, so it was not flowing, extending the rest of the layout. Now it should …
> ISSUE-80: WebArchiving my old friend

- js/mirador_strawberry.js
- js/plugin.iiif-iabookreader_strawberry.js
See #74 
Some JS magic to deal with missing/partial/missunderstood Manifests.  It does the following
- If service level is > 0 (means we have an info.json), append the get arguments to it (?page=1)
- If width/height is present but level == 0 (like static image or one we want o set because we are like that) then use the Canvas width/height ratio to calculate the missing one. (either height or width)
- If service level == 0 don't even bother trying to figure out an .info.json and in the worst possible condition just use the generic 3/4 ration and console it out so the webmaster/admin/can have nightmares and fix its Twig Template.
Gosh! @giancarlobi i know you out but someone needs to see this even if in 2 days. @alliomeria i need to introduce you IIIF Manifests sooner than later.
In …
> Issue 74b: IABookreader, please cooperate with old friend PDF?

- format_strawberryfield.libraries.yml
@giancarlobi Seven Theme (in Drupal 9) does not include modernizr anymore. We use it for the bookreader. Here is the patch!
> Updates JS to comply with Drupal 9 missing attachments

- composer.json
- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- format_strawberryfield.permissions.yml
- format_strawberryfield.routing.yml
- format_strawberryfield.services.yml
- js/iiif-iabookreader_strawberry.js
- js/iiif-openseadragon_strawberry.js
- js/mirador_strawberry.js
- js/w3cWebAnnon_strawberry.js
- src/Controller/JsWorkerController.php
- src/Controller/WebAnnotationController.php
- src/Entity/MetadataDisplayEntity.php
- src/EventSubscriber/formatStrawberryfieldDeleteTmpStorage.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Validation/Constraint/TwigTemplateConstraint.php
- src/Plugin/Validation/Constraint/TwigTemplateConstraintValidator.php
- src/TwigExtension.php
Weirdest Pull title ever. This is intended as a way of bringing a few features together that are already in 1.0.0-RC1 but do not live in  ISSUE-91 (the one with WebAnnotations) So @giancarlobi can test in D9 all together.
How to test? 
- Once Merged (and conflict solved)
- checkout and pull
- Enabled the new Permissions at least for the Admin and Web Annotations Viewing for Anonymous
- Go to any View Mode that is using the Media Formatter (OpenSeadragon), edit the Formatter settings and check the "Annotations" checkbox. Update and Save
- Using "Shift + Mouse" draw a box in any Image driven by Openseadragon. Add more, edit (delete per item is not working yet), answer, reply. Once done, press "Edit tab" you should see a new message in any form saying you have un persisted  Annotations. …
> Issue 91 into RC1 For Giancarlo to test on Drupal 9

- composer.json
- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- format_strawberryfield.permissions.yml
- format_strawberryfield.routing.yml
- format_strawberryfield.services.yml
- js/iiif-iabookreader_strawberry.js
- js/iiif-openseadragon_strawberry.js
- js/mirador_strawberry.js
- js/w3cWebAnnon_strawberry.js
- src/Controller/JsWorkerController.php
- src/Controller/WebAnnotationController.php
- src/Entity/MetadataDisplayEntity.php
- src/EventSubscriber/formatStrawberryfieldDeleteTmpStorage.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Validation/Constraint/TwigTemplateConstraint.php
- src/Plugin/Validation/Constraint/TwigTemplateConstraintValidator.php
- src/TwigExtension.php
See #91 
- Minor JS updates including most of our delivered viewers and libraries
- Updates to references to remote Images and assets
- Added Leaflet Marker Cluster, an old friend of mine (from back at Chile times) for larger maps
- Universal Viewer Core Library soon to be complemented with the rest of the framing, our own JS and the Formatter code
- A Twig extension to check the type (class) of an object, useful if you want to call NODE or User methods on unknown classes of Objects
- A Twig deprecation See #94 
- W3C Web Annotations with "adding", removing and updating directly on the Open Seadragon Viewer !(gosh am I good! hahaha) Tested and works. This also adds some new permissions and an almost full blown CRUD/REST API for the web annotations. Even work (designed so) with multi image …
> Issue-91: update JS libraries/Twig/Formatters and prepare of D9 deployment

- src/Entity/MetadataDisplayEntity.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
Tired, so just read #100, all the cuteness and jokes are there!
@giancarlobi @alliomeria we need to test this thoroughly. There are CORE changes and improvements added to rendering Twig templates but I want to be sure they work correctly in every possible case. Should not break (tasted here of course) and the BIG improvement of course is "optional", not everyone will need to push extra Data into a Twig template.
This also proofs (yeah) that Strawberryfields are awesome and can be used in other entities too.  I also want a piece of cake because I managed to remove Code from Archipelago making everything more slick and cute.
> ISSUE-100: Allow extra data to be pushed into a Metadata Display via its own custom fields

- format_strawberryfield.libraries.yml
- format_strawberryfield.routing.yml
- js/mirador_strawberry.js
- src/Component/HttpFoundation/RangedRemoteFileRespone.php
- src/Controller/IiifBinaryController.php
- src/Controller/JsWorkerController.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
Won't repeat. Its all here https://github.com/esmero/archipelago-deployment/issues/75#issue-745187010
Gist: large files leak memory when delivered via Range requests because Guzzle/AWS SDK and Symfony have issues 🤕 
Solution: we make the same requests we get back to the storage and only stream the bytes we need without offset on the PHP machinery. Sleek, elegant, hack-ish, perfect. Works
This also includes the new replay web 1.3.0 JS and Mirador 3.0.0 final.
Comes with bonus of a new version of PHP in our docker containers. 7.4.9. Nice and wazc tool to transform WARC files into WACZ files
> ISSUE-102: large files via Ranged request delivery, replay.web 1.3.0

- js/iiif-iabookreader_strawberry.js
@DiegoPino It seems due to how page height sum is rounded to calculate BRpageview element height. I found that set padding to 11 instead of 10 solves this issue with Archipelago. I don't see any collateral issues, please check if this is ok also for you.
> Fix IAB 1up mode off sync

- src/Controller/WebAnnotationController.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
So this adds a new mime type check for the web replay widget which matches our idea of how a WACZ file should be recognized since it derives from a frictionless data package. `application/vnd.datapackage+zip`. I will add another commit later where in the presence of both a WARC and a WACZ we prefer the later.
> ISSUE-109: Add the new WACZ mimetype

- format_strawberryfield.links.task.yml
- format_strawberryfield.module
- format_strawberryfield.routing.yml
- format_strawberryfield.services.yml
- src/Plugin/Block/DisplayInformationBlock.php
- src/Plugin/Menu/LocalTask/ViewModeLocalTask.php
- src/ViewModeResolver.php
- src/ViewModeResolverInterface.php
This PR adds the following:
- New block `DisplayInformationBlock` that shows the view mode selected linked to the display settings of that view mode
- A local task plugin to inject the right parameters to the Display settings tab per ADO (`ViewModeLocalTask`)
- A consolidated service: `ViewModeResolver` that is called in view_mode_alter but also in the informative block, it does the heavy lifting of selecting the view mode, caching the biggest and common part (getADOTypes)
> ISSUE-120: Added an admin hint block and tab for the ADO view mode display

- .gitignore
- config/schema/format_strawberryfield.schema.yml
- js/iiif-pannellum_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryDirectJsonFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
- src/Tools/IiifHelper.php
See #109 
A new base class for Formatters that need/want to extract Media from the JSON in a more fine grained way. This allows right now two extra JMESPaths to be defined and also 2 fallback options.
This also adds non related data that we found today. IIIF limits on Pannellum panorama Formatter/JS. Now we detect if the Device is Mobile or Not and also calculate (gosh) estimated memory usage based on the IIIF JSON provide size arrays. That way we avoid Java HEAP overflows with + 32K images when asking for more that 50%. you can always without any issues as for MAX size since those are served directly without any preprocessing/scaling from Cantaloupe. I also added + friction to help with #121
> ISSUE-109: Allow JMESPaths to define which media is used. WebReplay

- src/Plugin/Block/DisplayInformationBlock.php
This PR adds validations around the node context to ensure we don't try to render links without the required context
Resolves #132
> ISSUE-132: Fixed issue when context is empty for Display Information block

- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
This PR removes the container class from the iiif div so the width is always 100%. 
Also some minor coding style fixes
Fixes #125
> ISSUE-125: Full screen view cut in half w/ OpenSeadragon viewer

- format_strawberryfield.libraries.yml
- format_strawberryfield.module
- js/iiif-iabookreader_strawberry.js
- js/iiif-pannellum_strawberry.js
- js/lazyload_strawberry.js
- src/Form/IiifSettingsForm.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
See #135. Simple Lazyload using a class iiid-lazy. If `data-src` is used instead of `src` attributes in an `img` tag are used then we will only load those images once they enter then Viewport (+100px). had to make some small JS changes to deal also with Views that refresh via Ajax, and we may do better.
Also:
Fix on how we calculate memory usage for Large Panoramas. I now multiply by 3x (RGB) and stay as "discrete" as I can. This will need in the future a real setting based on how much XMX we gave Cantaloupe. For now 256mb is as conservative as we can go for large images. Images less than 16K can use 'MAX' to avoid derivative processing of course.
Last:
I tackled here (quickly) ISSUE-138 via Ajax @pcambra. Why? On large Objects, clearing caches the whole time while the NODE nor the image …
> ISSUE-135: Lazy load first attempt + Memory usage on Pannellum/Cantaloupe and regression on ISSUE-138 

- format_strawberryfield.install
The title is deceiving. WE are good people and we have a few D9 running, but it does not hurt!
@pcambra @giancarlobi could you both look at this? Nothing out of the normal except we are "patching" a hook that every archipelago live we have already had executed. But this is useful for from scratch deployments that have no .yml files supporting them or when the initial install failed?
I see no harm in this really
> ISSUE-142: retroactively be a good Drupal 9 citizen (which is like a time travel paradox?)

- composer.json
- src/TwigExtension.php
This is a simplified version of the original feature request: https://github.com/esmero/format_strawberryfield/issues/145. Rather than load entity data, this twig extension just loads entity ids of entities whose labels match the provided name.
Put something like the following example into your twig template, with tests for each of the supported entity types: node, taxonomy_term, user, group. 
Example: Given a field in the twig data with a name of a taxonomy term, get the first taxonomy term ids from all terms with that label in a particular vocabulary:
```
{% if data.term_name %}
{% set terms = sbf_entity_ids_by_label(data.term_name, 'taxonomy_term', 'my_vocabulary') %}
{% if terms[0] %}
"my_term":  {{ terms[0]|json_encode|raw }},
{% endif %}
{% endif %}
```
> WIP: Issue 145 -- Add twig extension for load entity ids by entity label

- format_strawberryfield.libraries.yml
- js/iiif-iabookreader_strawberry.js
- js/iiif-pannellum_strawberry.js
- js/plugin.iiif-iabookreader_strawberry.js
See #151 and https://github.com/esmero/webform_strawberryfield/issues/98
@giancarlobi this also fixes the IABookreader Search/Mode from URL autoloading. Issue was quite simple but it took me some time.
Since we are extending .init() and the search() we do not need to call the 
```JS
if (this.options.enableSearch && this.options.initialSearchTerm) {
this.search(
this.options.initialSearchTerm,
{ goToFirstResult: this.goToFirstResult, suppressFragmentChange: true }
);
}
```
During init(). That is called by the main/extended `_super` method
Please give it a test, at least here all worked!
> ISSUE-151: Hot Spot URLs and Fixes IABookreader load search and Mode (1up) from URL

- format_strawberryfield.services.yml
- src/Controller/MetadataExposeDisplayController.php
- src/Entity/MetadataDisplayEntity.php
- src/EventSubscriber/formatStrawberryfieldDeleteTmpStorage.php
- src/EventSubscriber/formatStrawberryfieldInvalidateMetadataCaches.php
- src/TwigExtension.php
See #155 but also new here:
New Cache tags that complement the the normal `Node` ones, that allows us to invalidate the Metadata Displays and exposed metadata Displays render caches on a Child Object change. This is needed to allow fast refreshing/real time changes on IIIF Manifests shown on a Creative Works Series or a Collection ADO when a new Child is added/deleted or updated since the Viewer (Mirador or any other IIIF Compliant one) will be cached based on the current Node(a.k.a the Collection) and since that one won't have changed (just the child pointing back) the data/images will be stuck
This includes a Invalidation  Event Subscribers and makes use of a Computed Field we have that  tracks all related ADOs to ADOs relationships across a whole SBF JSON
I also added a user.role …
> ISSUE-155: Add new JSON_DECODE twig filter and parent ship Cache tags for Metadatadisplay

- js/iiif-pannellum_strawberry.js
See #164
Adds Autoload property for global Tour Viewer from the global settings as we do for individual Panoramas.
Its a single line so not a big issue but super needed.
> ISSUE-164: Add Autoload property for global Tour Viewer

- src/Controller/MetadataExposeDisplayController.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
See #177. This really applies to any Formatter and only fails if there is no media at all to show. This fixes it but @aksm @alliomeria @giancarlobi I'm not totally happy still with the refactor for formatters. I might push another (different issue) before 1.0.0
@giancarlobi can you please test tomorrow?
Thx
> ISSUE-177: Initialize embargo cache arrays sooner

- src/Element/EntityAutocompleteUUID.php
See https://github.com/esmero/format_strawberryfield/issues/187
@patdunlavey @alliomeria and thanks for @aksm to hitting this one. So annoying!
PS: when coming from an early RC3 or a RC2 the key value will be already filled and it won't fail of course.
> ISSUE-187: Wrong key value collection for UUID based Metadata Display Entity Autocomplete element for 1.0.0

- src/Element/EntityAutocompleteUUID.php
See #187 
@patdunlavey @alliomeria and thanks for @aksm to hitting this one. So annoying!
PS: when coming from an early RC3 or a RC2 the key value will be already filled and it won't fail of course.
> ISSUE-187: Wrong key value collection for UUID based Metadata Display Entity Autocomplete element

- config/schema/format_strawberryfield.schema.yml
- src/Plugin/Condition/AdoType.php
This is a fairly simple condition plugin that permits conditioning block display and contexts on the ADO Type of the current node.
See https://github.com/esmero/format_strawberryfield/issues/221
Potential changes/improvements:
- Use a solr facet search to create the list of ADO Types for the configuration form, rather than depending on the presence of the two webform options lists.
- Would changing to a solr search for the current node's ADO type be more performant? Or caching?
- I didn't bother implementing javascript to display the context summary, which seems superfluous. Is that needed?
Requesting review from @aksm
> ISSUE-221 --- ADO Type condition plugin.

- composer.json
Reverts esmero/format_strawberryfield#228
Needs better testing with citeproc-php version string.
> Revert "ISSUE-227: Add citeproc-php to composer.json"

- composer.json
Resolves #227. The original merge was reverted because it wasn't tested, but this one has been tested. composer.lock and composer.default.lock files will have to be updated  (and tested) on archipelago-deployment and archipelago-deployment-live.
> ISSUE-227: Add citeproc-php to composer.json

- config/schema/format_strawberryfield.schema.yml
See #237
Please check if I got it right this time? @patdunlavey @aksm 
Thanks for reporting
> ISSUE-237: bad indentation for UV formatter schema

- composer.json
- config/schema/format_strawberryfield.schema.yml
- src/CiteProc/Render.php
- src/Element/EntityAutocompleteUUID.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
Resolves #236 for branch 1.1.0.
The check for NULL was already there. Just needed to move the rest of the metadata display entity rendering into the try block.
> ISSUE-236: Citation Formatter check for null

- js/mirador_strawberry.js
See https://github.com/esmero/format_strawberryfield/issues/244
I replicated Diego's [solution for video player links in Mirador](https://github.com/esmero/format_strawberryfield/commit/c823b3eb459bf1327619a0064dc9c3e9b951c6b2) to work for audio player links.
To test, create an ADO with multiple audio files and configure the ADO type to display using the Mirador viewer and IIIF Presentation 3.0 API.
> ISSUE-244 --- Workaround Mirador to allow mutiple Audios on Chrome/Firefox

- src/Plugin/Condition/AdoType.php
See https://github.com/esmero/format_strawberryfield/issues/249
Requiring the 'ado_types' field to be required causes drupal's block configuration forms to become unsubmittable, and context conditions to sometimes become unsubmittable if the form tab is hidden when the user tries to submit the form. This PR solves the problem simply by removing the "required" attribute, since `format_strawberryfield\Plugin\Condition\AdoType::evaluate` handles the case of this field being empty just fine.
> ISSUE-249 --- removed '#required' from the 'ado_types' field in the ADOType condition configuration form

- src/Controller/MetadataDisplaySearchController.php
This PR updates the JMESPath constants for both IIIF Presentation v2 and v3 to fix some potential issues.
**Problem:** Non-Image services could be picked up by the selector.
**Fix:** Add a filter clause to make sure the `@context` block of the service is for an Image API version. The reason for using this field is per [Presentation 2.1.1 section 5.4](https://iiif.io/api/presentation/2.1/#image-resources): "A reference to the Image API context document **MUST** be included", so on a valid Manifest it will be present.
**Playgrounds:**
1) Current code, picking up Search service in third canvas: http://play.jmespath.org/?u=926ccfd3-0b1f-43b2-b431-b9c9b3bdbf93
2) Fixed code, picking up Image services for Canvas 1+2, and not the Search service in Canvas 3: …
> Issue 248 patch - Update JMESPaths

- src/Controller/MetadataDisplaySearchController.php
A small optimisation to the V3 path that avoids the need to store `@id`/`id` and `@type`/`type` in temporary hashes, and just assigns them straight away.
Playground: https://play.jmespath.org/?u=5ad1f201-12d6-46aa-96bf-9174c6541a7a
> Small improvement to `IIIF_V3_JMESPATH`

- src/TwigExtension.php
See #247 
- Better validating the Result type of data
- Changed a limit
Won't go crazy with Strawberry Flavor results
Needs probably more testing/more exception catching
> ISSUE-247: Fixes Search API twig extension

- css/iabookreader.css
- js/iiif-iabookreader_strawberry.js
Resolves #167.
Phew, that was an unexpected journey. The Javascript and CSS are not ideal, but between clashing library themes, I did the best I could do. Needs some testing, particularly regarding the page/book URLs being generated and the various platform share URLs being generated/updated.
> ISSUE-167: Style "share" pop-up window for IA Bookreader

- format_strawberryfield.routing.yml
> ISSUE-223: Provide media/files at UUIDs additionally to node IDs

- format_strawberryfield.links.task.yml
- format_strawberryfield.routing.yml
- modules/format_strawberryfield_facets/config/schema/format_strawberryfield_facets.schema.yml
- modules/format_strawberryfield_facets/css/slider.css
- modules/format_strawberryfield_facets/format_strawberryfield_facets.info.yml
- modules/format_strawberryfield_facets/format_strawberryfield_facets.install
- modules/format_strawberryfield_facets/format_strawberryfield_facets.libraries.yml
- modules/format_strawberryfield_facets/js/date-range.js
- modules/format_strawberryfield_facets/js/slider.js
- modules/format_strawberryfield_facets/src/Plugin/facets/processor/DateRangeProcessor.php
- modules/format_strawberryfield_facets/src/Plugin/facets/processor/RangeSliderProcessor.php
- modules/format_strawberryfield_facets/src/Plugin/facets/processor/SliderProcessor.php
- modules/format_strawberryfield_facets/src/Plugin/facets/widget/DateRangeWidget.php
- modules/format_strawberryfield_facets/src/Plugin/facets/widget/RangeSliderWidget.php
- modules/format_strawberryfield_facets/src/Plugin/facets/widget/SliderWidget.php
- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/format_strawberryfield_views.module
- modules/format_strawberryfield_views/format_strawberryfield_views.routing.yml
- modules/format_strawberryfield_views/format_strawberryfield_views.services.yml
- modules/format_strawberryfield_views/js/facets-views-ajax.js
- modules/format_strawberryfield_views/js/modal-exposed-form-ajax.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Controller/ViewsExposedFormModalBlockAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
- modules/format_strawberryfield_views/src/Routing/RouteSubscriber.php
See #260 
- Adds a special Filter named Advanced Search capable of handling multiple inputs with Boolean Operators
- Overrides the Default AJAX controller to NOT fail if the default Exposed Form is not present (Ajax ends clearing all Settings if that is the case, bad sloppy Drupal)
-  New Block Plugin (Modal Exposed Views Form) that allows selectively to hide/show Exposed Form elements providing a variety of cool options. Has a deriver
- Ajax to drive updates of Modal Exposed Views Forms (many on a single site) that is aware of Facet Summaries and Facets, overriding the default Facet JS which is (guess what) also sloppy
- New Facet Summary Processor that is able to show Active Selected Facets even if no results. Does some crazy pants stuff to reverse-engineer what normally the actual …
> ISSUE-260: Views and Facets  + advanced search

- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
See #269 
When using a single Media Source all present VTTs (independently where) are going to be used. Also adds the Filename as part of the VTT label on the player. The old behavior still works, grouped VTTs/Media will be treated as such.
> ISSUE-269: Lower the strict conditions for a single Media (audio and video) with VTT(s)

- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
See #271. Includes some fixes for Advanced searches (Direct Parser) where we know (now) that Drupal's Parse Mode Parser DOES NOT know how to deal with an empty and we end with just the `#conjunction` which means a wrong Parsed Solr query. This filters out anything that after trimming == '' but preserves spaces on the query term if that is not the case.
There might be other "Edge" cases but we can start with what we know right?
> ISSUE-271: Deal with Empty Queries on Advanced and Facet Summary for Queries

- format_strawberryfield.routing.yml
- modules/format_strawberryfield_facets/config/schema/format_strawberryfield_facets.schema.yml
- modules/format_strawberryfield_facets/src/Plugin/facets/processor/SbfExcludeSpecifiedItemsProcessor.php
- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/format_strawberryfield_views.module
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
See #280 
This also includes
- Small update to the `format_strawberryfield.display_settings:` route to allow a pattern that is not based only on dynamic pieces and thus not interferes when trying to add Views as tabs
- Small fix for our Empty results facet summary processor (in case there is no query at all) + start of better config schemas
> ISSUE-280:Exclude Facet Processor that allows multiline facet value settings

- js/clipboard_copy_strawberry.js
Resolves #265. The data attribute used for the copy button's CSS classes can contain a space-separated list. Once this is merged 2 small updates can follow:
1. Open PR for documentation around this copy/paste functionality should be updated.
2. Javascript for the IA Bookreader share functionality can be slightly refactored to be cleaner.
> ISSUE-265: Allow multiple CSS classes for clipboard copy functionality

- modules/format_strawberryfield_facets/config/schema/format_strawberryfield_facets.schema.yml
- modules/format_strawberryfield_facets/src/Plugin/facets/processor/DateRangeProcessor.php
- modules/format_strawberryfield_facets/src/Plugin/facets/widget/DateRangeWidget.php
- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
See #283 
This one was tricky. Gist: To generate a "unselect the current facet" you have to build all active facets except the one you want to unselect. When there are no ones (means the current, in this case our custom range) Facet Module suggests (copied the code) to use a HTTP REQUEST based parser method that gets confused when a single View (Facet Source) has multiple Displays (specially if those display are not 1:1).
The solution was not terrible.
Now that this is working I also made "quoting" the Full Text Search Terms Facet Summary (part of this pull)
> ISSUE-283:Facet Summary Processor misbehavior on Date Range when it is the only Facet selected

- format_strawberryfield.module
- src/Entity/MetadataDisplayEntity.php
- src/Form/MetadataDisplayForm.php
Start on resolving #274 with refactor to the below to replace deprecated classes. https://github.com/esmero/format_strawberryfield/blob/2e5cc2a6f882cd2490caccc2cbd5b88b58f70c0f/src/Entity/MetadataDisplayEntity.php#L435-L459
> ISSUE-274: Report render array output error in Metadata Display preview

- modules/format_strawberryfield_views/format_strawberryfield_views.module
- modules/format_strawberryfield_views/js/modal-exposed-form-ajax.js
- modules/format_strawberryfield_views/src/Ajax/SbfSetBrowserUrl.php
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/StrawberryFlavorsJoin.php
See #290 
- Adds Solr 9.x Awareness of HL/Overridden at Solarium level defaults
- Better HL processing for JOINS coming from a normal Full Text Filter. Uses ORs for the subquery and removes any negations
- Huge stupid bug found in Advanced Search that was carrying previous Fields into the next filter and thus making queries almost never match what one wanted. Good!
- Ajax Views now keep browser state and are shareable/linkable/book-markable. Clear your browser Cache since this is JS
> ISSUE-290: Solr 9.x and better HL for joins and Advanced search JOIN awareness

- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
Still part of #290 (sorry @alliomeria )
`op` is being kept in the Ajax/browser state (thing I used for having bookmarks) and bc ops is used to add fields/remove files and submitting, we are having conflicts when doing advanced search + this.
@alliomeria reason is "op" is basically a submit. You don't want to have a submit on the browser history bc it will clash with the actual submit and drupal is not smart enough to discern "data is coming from Ajax or GET", get will win
> ISSUE-290b: Remove op query parameter from the Browser state 

- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
$query_able_data gets iterated twice, the first time with its members called $query_able_datum_fields, and the second time as $query_able_datum_internal. During the second round of iterations ($query_able_datum_internal), the $query_able_datum_fields variable was referenced, which may or may not be the same as the current $query_able_datum_internal variable. When it is the same, no problem. But when it's not, the $query_able_datum_fields['aggregated'] may not be an array.  This causes \Drupal\search_api_solr\Utility\Utility::flattenKeys to fatal error.
The fix is to change out $query_able_datum_fields['aggregated'] for $query_able_datum_internal['aggregated']. 
For good measure, I added in extra validity checking for $query_able_datum_internal['aggregated'], though I don't think it's …
> ISSUE-304 --- Use the correct variable name for the aggregated fields

- css/metadatapreview.css
- format_strawberryfield.libraries.yml
See #313 
This also now makes the Preview button sticky/solves the overlay. Much easier for editing/previewing while you work @alliomeria @karomabiles !
> ISSUE-313: Save button on Metadata Display Preview on default theme is under Code Mirror

- src/Entity/MetadataDisplayEntity.php
See #315 
@alliomeria this fixes the error we saw (I showed/sorry) today. @aksm I will merge but the code needs really more testing. Try please with more custom twig (valid) to really validate. There might be more/future pulls needed. When this happens bc of the data/use processing previewing is simply impossible.
> ISSUE-315: Twig nodes accessor to non-existing name attribute throws exception

- src/Form/MetadataDisplayForm.php
As explained on #320 we need more testing and live work with @aksm before using this code live. Templating preview can't fail for reasons that the user writing the template has no control over. We will work on getting this right before the release (next week)
> ISSUE-320: Disable Variables and Custom Error handler from Twig preview until more tests have been done

- src/Plugin/Field/FieldFormatter/StrawberryDirectJsonFormatter.php
See #323
Basically the issue is when using formatters we have a form inside a form (multiple fields, each one with a formatter via fields_ui but layout builder moves this out to its own structure) breaking our expected #parents key needed for JMESPATH validation.
Also note: when upgrading to DS 3.15, disabling and re-enabling core Layout Builder, Layout Builder or DS can be used without having to disable DS totally. It requires some "playing around" but it actually works. Maybe something we want to offer for the release?
> ISSUE-323: Layout Builder uses a totally different Field UI render array

- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/css/advanced_search.css
- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/format_strawberryfield_views.module
- modules/format_strawberryfield_views/js/modal-exposed-form-ajax.js
- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
See #326 
First one:
Submit on enter (not add one/remove one on Enter)
So much code for such a simple thing @alliomeria . Stuff is: Browsers will always pick the first submit found, so rendering order leads. If i put search first then other stuff like adding a + button by each one will still fail (future needs). Also Drupal will make all  buttons input type=submit (if we want to pass stuff via form state) so i have to alter the form, intercept the Enter and trigger the only and only one (staring at the moon) button i care for (i care of other things, like plants and some people and trees and moonshine)
Second: no more stuck keywords on remove one, add one. I changed the whole logic, drupal is so buggy. Now Add more/remove one act on pure JS, change values and then autosubmit (via drupal). …
> ISSUE-326: Advanced search community needs

- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
See #329 
This will end in a V1.1.1 tag but on the current dev-1.1.0 branch (I know what I am doing, don't judge me!)
> ISSUE-329: Fix imprecise JS on Advanced Search when multiple exposed forms are rendered

- modules/format_strawberryfield_views/format_strawberryfield_views.module
Gosh
See #331 
The autofocus on every page on the submit button is annoying. Functional OK. But theme wise something a theme can do outside of our code. Removing.
> ISSUE-331: Removing autofocus on Views Exposed form Submit buttons

- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- src/Controller/IiifBinaryController.php
See #334. Symfony provides its own implementation inside the `::prepare` option but it is limited to a smaller/different/subset of mime types and will not work for model/obj etc leading to text. Better to use the already calculated one like we do in the ranged controller section/streamed controller section already. Tested and this does not affect any other implementation and plays well with AMI too
This also solves #333 (since I was here)
> ISSUE-334: Provide a manual Content-Type for the plain Binary Controller

- src/Controller/IiifBinaryController.php
See #334 and https://github.com/esmero/ami/issues/173
What? Work around. If we ended migrating Files from badly setup Fedoras/Islandora we can at least at the last minute provide canonical Mime Types. I can not update Files here. We can build then an update hook for files in 1.2.0, if needed, that does this.
> ISSUE-334b: Add exceptions for past wrongly provided mime types by remote sources

- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/views/display_extender/StrawberryAjaxInteractions.php
See #345 
Also did a small work-around a bug in Drupal: A non valid (bc I messed it up) Views Page Path will still render a page but basically not work. In that case I can not generate a browser history. I mean nothing will work, but at least it won't be because of our code.
Also the wording of our display extender was "improved". We only allow relationships and Contextual filters to be "fed" by a viewer/ado. Not pure exposed filters that could be modified by the user via a form (that would be a great/extra mess if we did).I mean, an exposed filter "could" be used, but only if also used as contextual. You all know what I mean (or not!)
@alliomeria this solves the array error we saw today.
> ISSUE-345: left over SBF Ajax interactions when enabling Ajax, then enabling interactions, then disabling Ajax again

- src/Form/MetadataDisplayForm.php
Resolves #343. Adds a static function that inserts a container with an error status at the top of the Metadata Preview modal if there is an error message and replaces the error messages that were being displayed in the details tabs.
> ISSUE-343: Metadata Preview error display

- config/schema/format_strawberryfield.schema.yml
- js/jsm-model_strawberry.js
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
Also includes a better (but not perfect yet) camera culling/clipping. Need more lights? Ask!
See #337 
This solves the issue by allowing a Formatter setting/or per ADO Camera Up vector override.
For the later use:
```JSON
{
"ap:viewerhints": {
"strawberry_3d_formatter": {
"cameraUpVector": [
0,
0,
1
]
}
}
}
```
> ISSUE-337: Allow Camera UP vector to be overriden by setting or metadata

- src/Plugin/Menu/LocalTask/ViewModeLocalTask.php
See #348 
This tries to get around the exception that happens when a View uses %node as a parameter, but does not upcast it the value to NodeInterface. It (of course) does this without too much overhead, which means it does not processes the View  Entity Itself and we simply assume a `view_id` + `node `argument are reasons enough to enrich the Route. It is important to node that really only place where this can happen (so pretty edge case) is when a View's path is node/%node given that (fixed in code) that is where our Route (Active Display settings) will call this class. Basically when Node level Tabs (actions) and View level Actions depend on each other/live side by side.
> ISSUE-348: Adds a pseudo Node "Upcaster" for Routed Views in the presence of "Active Display Settings" tab

- config/schema/format_strawberryfield.entity.metadataexpose_entity.schema.yml
- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.install
- src/Controller/MetadataExposeDisplayController.php
- src/Entity/MetadataExposeConfigEntity.php
- src/Form/MetadataExposeConfigEntityForm.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryUVFormatter.php
See #353, Closes #353
This adds a new Setting to IIIF enabled Viewers that allows a formatter to block the display of a Viewer completely. This allows users that don't want/know how to use the `data.data_embargo.embargoed` and `data.data_embargo.until` Metadata Display context variables to act/modify a IIIF Manifest  (or any Template driven output) on the presence of an embargo, to hide the Viewer completely. 
@alliomeria thanks
> ISSUE-353: Hide viewer if embargo is present + enforce embargo on Exposed Metadata Endpoints via 401

- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
See #363 
This value can be in fact be null but bc we have to compare (when it has one) against valid sources, so we do an array filter and break hell loose. This should fix it
> ISSUE-363: Wrong empty defaults break View Ajax settings on Map formatter

- format_strawberryfield.libraries.yml
- js/leaflet_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryBaseIIIFManifestFormatter.php
- src/TwigExtension.php
`edtf_2_iso_date` which is a filter returns always an array. Either empty if we could not parse it, wrong data, etc. a single 'Y-d-m' value or two  'Y-d-m' if a range/uncertainty with 2 possible dates.
> ISSUE-368: edtf_2_iso_date

- format_strawberryfield.routing.yml
- src/Controller/MetadataDisplaySearchController.php
- src/Tools/IiifHelper.php
See #248 
Implements a better / way more flexible (but still a bit slow, will add cache I promise) to search using the same display side IIIF manifest to parse out page Order. This is so far meant to solve the IABookreader need but will grow (don't merge yet) into a valid IIIF Search API too.
TODO: Need to add some config options and it depends on some improvements on SBF 1.1.0 too (which can be pushed and merged without this one).
Will add some config instructions when ready for a merge. 
@patdunlavey @aksm
> ISSUE-248: backend (metadata display) driven Search for OCR

- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/src/Plugin/views/style/LeaftletGeoJSON.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseIIIFManifestFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
See #384 
But really the important bit is:
`$mediasource = array_filter($mediasource);`
> ISSUE-384: Fixes Manifest v/s Image driven OSD issue with configuration default/formatter settings form

- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
Also fixes wrong #state selector (was not wrong, but Drupal ... gosh... )
See #387
> ISSUE-387: always pass viewer_overrides as part of the DrupalSettings to JS

- modules/format_strawberryfield_rest_oai_pmh/src/Form/FormatStrawberryfieldRestOaiPmhSettingsForm.php
Needed explicitly in D10
See #389 
Even with this I can't make this module work on D10/Search API Solr driven view even using the 2.x-dev version of the module this extends. The issue (so far) is that the custom Caching system it uses is so DB based that it can not extract correctly an entity type (in a generic way) from the used and configured view. Maybe we need to discuss this module?
> ISSUE-389: add accessCheck() to FormatStrawberryfieldRestOaiPmhSettingsForm.php

- src/Controller/MetadataExposeDisplayController.php
- src/EmbargoResolver.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryUVFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
See #395 
This has been tested a lot. But I will give my today's self a bit of slack, test again later tonight and merge. Solves the issue with Anonymous users from a different IP/Network seen a stale cache generated by other anonymous users + makes also cache more robust on all viewers +  brings to 2023 the simpler image formatter nobody uses (a "classic")
> ISSUE-395: Make IP based embargoed ADOs + Anonymous users un-cacheable

- format_strawberryfield.links.task.yml
- format_strawberryfield.routing.yml
- format_strawberryfield.services.yml
- src/Entity/Controller/MetadataDisplayListBuilder.php
- src/Entity/MetadataDisplayEntity.php
- src/Form/MetadataDisplayUsageForm.php
- src/Form/ViewModeMappingSettingsForm.php
- src/MetadataDisplayUsageService.php
- src/MetadataDisplayUsageServiceInterface.php
see #397 
Just opening the pull even if this is so far just an UI experiment (table? checkboxes? containers? who knows, not super inspired today)
Will keep pushing code until I feel the UI/UX is intuitive
> ISSUE-397: Adds Usage Tab to Metadata Display Entities

- composer.json
- modules/format_strawberryfield_views/js/modal-exposed-form-ajax.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Controller/ViewsExposedFormModalBlockAjaxController.php
See #385 
This enables us to move forward with Drupal 10.1. Views now use by default GET which also means the arguments we need for our overrides for facets/ custom exposed form block approach are somewhere else. 
I'm not sure of these changes work with 10.0.x so for now will pull against 1.3.0 but might have to change my mind and roll YET another release. (thanks blue drop)
> ISSUE-385: Drupal 10.1 compatibility for our overriden Controllers/facet/exposed forms (Symphony 5 v/s GET)

- composer.json
- format_strawberryfield.info.yml
- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
See #400 
This is ready to be tested.
New settings:
Classic mode basically uses JS for everything but keeps the sequential logic of fields named with a suffix `_$count` and ordered. Does not solve the other need (facet summaries)
> ISSUE-400: Advanced Search Classic mode

- composer.json
- format_strawberryfield.info.yml
- modules/format_strawberryfield_facets/config/schema/format_strawberryfield_facets.schema.yml
- modules/format_strawberryfield_facets/src/Plugin/facets_summary/processor/LastActiveFacetsProcessor.php
- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/js/facets-views-ajax.js
- modules/format_strawberryfield_views/js/sbf-advanced-search-default-submit.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
See #404 . I will keep pulling this against 1.4.0 but maybe we can just make all 1.3.0 and then close the Restaurant, turn the tables and wash the dishes?
Who knows
> ISSUE-404: Facet summary with separate entries per Input/field for advanced search

- format_strawberryfield.module
- src/Controller/MetadataExposeDisplayController.php
- src/EmbargoResolver.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryUVFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
see #412 
This pull makes something wonderful. Embargoes are still resolved per Entity. (and I can do better I know and will) on each SBF formatter call/exposed endpoint etc. But the response is statically cached and accumulated during an HTTP request (means 10 fields == 1 calculation). We still `kill` the page cache & dynamic cache if there is an IP embargo for an object (even if resolves to not embargoed bc there is no context/saved data in Drupal I can use to differentiate on Anonymous from another, all comes in the request itself), but also (to make Drupal's weirdness/lack of consistency) happy, just after the  View Mode/Display (ignoring the internal render array elements) decides to cache everything, we make the cache time to live == 0 for the whole Node. And bum. It works.
How to …
> ISSUE-412: Tested on production. Finally IP embargoes can cut the Cache crap

- config/schema/format_strawberryfield.schema.yml
- js/leaflet_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
1.4.0 version of [this PR](https://github.com/esmero/format_strawberryfield/pull/415)
- Added leaflet map option for 'Disable …mouse wheel zoom'. 
- Reduced the minimum map height to 62px, which guarantees that the +/- buttons will display.
- Edit "Map Display for Digital Objects SQL view (`/admin/structure/views/view/map_display_for_digital_objects_sql`) view
- Click on the field settings for "Content: 🍓 Strawberry (Descriptive Metadata source)" to bring up the configuration form for that field.
- Test the view with different values for "Maximum height". Any height equal to or larger than 62 pixels should be able to be saved, and should be reflected in height of the map that is displayed when the view is rendered for an object.
- Set the "Disable mouse wheel zoom" checkbox to unchecked …
> Issue-414-1.4.0--leaflet-options --> 1.4.0

- config/schema/format_strawberryfield.schema.yml
- js/leaflet_strawberry.js
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
- Added leaflet map option for 'Disable mouse wheel zoom'. 
- Reduced the minimum allowable leaflet map height to 62px, which guarantees that the +/- buttons will display while permitting map heights smaller than 480 pixels.
- Edit "Map Display for Digital Objects SQL view (`/admin/structure/views/view/map_display_for_digital_objects_sql`) view
- Click on the field settings for "Content: 🍓 Strawberry (Descriptive Metadata source)" to bring up the configuration form for that field.
- Test the view with different values for "Maximum height". Any height equal to or larger than 62 pixels should be able to be saved, and should be reflected in height of the map that is displayed when the view is rendered for an object.
- Set the "Disable mouse wheel zoom" checkbox to unchecked (it's the …
> Issue-414--leaflet-options --> 1.3.0

- modules/format_strawberryfield_views/format_strawberryfield_views.libraries.yml
- modules/format_strawberryfield_views/format_strawberryfield_views.module
- modules/format_strawberryfield_views/format_strawberryfield_views.routing.yml
- modules/format_strawberryfield_views/js/modal-exposed-form-ajax.js
- modules/format_strawberryfield_views/js/modal-exposed-form-interactions.js
- modules/format_strawberryfield_views/js/sbf-views-ajax-dynamic.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
see #427
This includes now also:
- Override for poorly coded thing in Drupal that does not allow nested Ajax Views Pagers
- Option to allow an on-click (`data-sbf-view-event="click"`)  or on-load (`data-sbf-view-event="load"`) for loading dynamically Views
- Works perfect. Just don't use the mini-pager because there is something wrong with it? Like globally (not us/but on them)
Tested with dozens of children, each child with 3K children. Paging works. All works!
> ISSUE-427: Adds data property (HTML) driven on click or on load Views loading via AJAX

- format_strawberryfield.libraries.yml
- src/Controller/IiifBinaryController.php
- src/Controller/JsWorkerController.php
see #434 
All this to please RFC, avoid NGINX stripping out our headers. Also updates replay.web to 2.0.0-beta
> ISSUE-434: Fix 206 response on a HEAD with a Range to a 200

- src/Controller/MetadataAPIController.php
- src/Form/MetadataAPIConfigEntityForm.php
See #442 
More code to come @alliomeria
> ISSUE-442:Open API sanity + Controller cleanup

- js/mirador_strawberry.js
See #453 
To test, add this to the settings (Mirador settings are confusing.. this is how you put the thumbnail navigation for the first opened window to the right.
```JSON
{
"windows": [{
"thumbnailNavigationPosition": "far-right"
}]
}
```
@alliomeria :eyes:
> ISSUE-453: Fixes Override Windows (array) loosing Manifest ID when overridden 

- src/Controller/IiifContentSearchController.php
- src/Controller/MetadataExposeDisplayController.php
- src/Entity/MetadataDisplayEntity.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseIIIFManifestFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
see #457 
I will make this 1.4.0 (since release happened but we are always allowed to make fixes until we start 1.5.0 branches & publish the release itself as a ZIP). 
This is not ready yet. I want to check what is happening with the SBF_ Aggregator processor and why it is triggered when the type of query has full processing ... Drupal gosh.
> ISSUE-457: Multiple bug fixes and improvements for Content Search API (Plain Text)

- js/mirador_strawberry.js
- modules/format_strawberryfield_views/js/facets-views-ajax.js
- modules/format_strawberryfield_views/js/sbf-views-ajax-interactions.js
- modules/format_strawberryfield_views/src/Controller/FormatStrawberryfieldViewAjaxController.php
- modules/format_strawberryfield_views/src/Controller/ViewsExposedFormModalBlockAjaxController.php
- modules/format_strawberryfield_views/src/Plugin/Block/ViewsExposedFilterBlockModal.php
- src/Form/MetadataDisplayForm.php
See #459 
Also brings some Changes/fixes that happened for Drupal 11
https://git.drupalcode.org/project/drupal/-/commit/ef985e937c58257c4f73f034cfd9b828430f9ad6
> ISSUE-459: Ajax/Facet/Views improvements  + ML similarity contextual filter and facets and 10.3 compatibility

- modules/format_strawberryfield_views/src/EventSubscriber/SearchApiSolrEventSubscriber.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/StrawberryADOJoin.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/StrawberryADOfilter.php
- modules/format_strawberryfield_views/src/Plugin/views/filter/StrawberryFlavorsJoin.php
- src/Form/MetadataAPIConfigEntityForm.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
See #472 
Needs https://github.com/esmero/strawberryfield/pull/339 so Backend Highlights for JOINED Flavors are queried using the name SBF to ADO (NID) relationship fields and thus match the hits
> ISSUE-472: Passes correctly multiple SBF to ADO relationships on JOINs

- src/Form/ViewModeMappingSettingsForm.php
- On ado type to view mode mapping form, use the strawberryfield.archipelago_solr_settings.ado_type field configuration rather than assuming 'type_1' for the solr field that indexes the ado type.
See [ISSUE-481](https://github.com/esmero/format_strawberryfield/issues/481)
> ISSUE-481 -- Remove hard-coded ado type field in ado type to view mode mapping form

- format_strawberryfield.install
- format_strawberryfield.libraries.yml
- format_strawberryfield.services.yml
- js/iiif-archipelago-interactions_utils.js
- js/mirador_strawberry.js
- modules/format_strawberryfield_views/js/sbf-views-ajax-interactions.js
- src/Controller/MetadataAPIController.php
- src/Controller/MetadataExposeDisplayController.php
- src/Entity/MetadataDisplayEntity.php
- src/TwigExtension.php
See #479 
works like this
```Twig
{{ sbf_file_content("uuid_of_the_node", "uuid_of_the_file", "thename.jsonld")|raw }}
````
Will return the content of a file if found/matches one of the mimetypes defined as valid for our metadata displays, now defined as constants at
```PHP
CONST ALLOWED_MIMETYPES = [
'text/html' => 'HTML',
'application/json' => 'JSON',
'application/ld+json' => 'JSON-LD',
'application/xml' => 'XML',
'text/plain' => 'TEXT',
'text/turtle' => 'RDF/TURTLE',
'text/csv' => 'CSV',
];
```
an error message in case of exception or an empty string if the file does not exist, the user has no permission, is not of an allowed  type, etc (avoiding as much as possible errors)
Also fixes #483 
@alliomeria more tomorrow bc this solves VARIOUS use cases
> ISSUE-479: Adds the sbf_file_content extension

- src/MetadataDisplayUsageService.php
on AMI sets Drupal 10.3+. See #492 
The error is super silly.
> ISSUE-492: Fix invalid render array for Metadata display usage 

- format_strawberryfield.module
- format_strawberryfield.permissions.yml
- src/Controller/MetadataAPIController.php
- src/Controller/MetadataDisplaySearchController.php
- src/Controller/MetadataExposeDisplayController.php
- src/EmbargoResolver.php
- src/EmbargoResolverInterface.php
- src/Entity/MetadataDisplayEntity.php
- src/Form/EmbargoSettingsForm.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryUVFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
- src/Plugin/views/argument_validator/ADOAccess.php
> ISSUE-510: New embargo (global) options + ADO Argument validator for Views + Refactor embargo service

- config/schema/format_strawberryfield.schema.yml
- format_strawberryfield.module
- src/Controller/IiifBinaryController.php
- src/Controller/MetadataAPIController.php
- src/Controller/MetadataDisplaySearchController.php
- src/Controller/MetadataExposeDisplayController.php
- src/EmbargoResolver.php
- src/EmbargoResolverInterface.php
- src/Form/EmbargoSettingsForm.php
- src/Plugin/Field/FieldFormatter/Strawberry3DFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryCitationFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryImageFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMapFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMediaFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMetadataTwigFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryMiradorFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPagedFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryPdfFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryUVFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryVideoFormatter.php
- src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php
See #510 
Note for @alliomeria. Many already were hiding on embargo automatically EVEN without the checkbox. We only added the checkbox to IIIF driven ones (Mirador/OSD/UV), bc those would also allow the user to act at the template level, so the extra flexibility was needed.
With this now in place (unified UI). one could actually end in a more "insecure" situation for viewers that were automatically secured before. That is why I made the default == TRUE.
We will have to doc.
I even added the option for Maps and Metadata Displays, so one could actually hide "Object Description" completely if one wanted to do so.
This also includes now "Direct/At the file level" resolved embargo + finally removed the (X) mark on hidden viewers
> Issue 510b: Adds Explicit "hide on embargo" checkboxes to all Field Formatters (means Viewers too) + File Embargo

- src/Controller/MetadataAPIController.php
- src/Form/MetadataAPIConfigEntityForm.php
See #516 
The configurable Token will only act on results driven by Views that are = limit defined in the Views.
Means if you request a listing, you get 6, The view that drives the listing is set for 25, no resumption token
The actual token can be found at only in the wrapper
at
```
{{ data_api.resumption_token|json_encode }}
```
it is a 3 valued array, first entry the name used in the arguments (for OAI it would be resumptionToken), second the expanded query, equivalent to passing the resumptionToken and finally the value
e.g 
```
["resumptionToken","?verb=ListRecords&metadataPrefix=oai_dc&set=6de8e0f9-62d2-4d1a-8e25-956130cb9096&page=2","P3ZlcmI9TGlzdFJlY29yZHMmbWV0YWRhdGFQcmVmaXg9b2FpX2RjJnNldD02ZGU4ZTBmOS02MmQyLTRkMWEtOGUyNS05NTYxMzBjYjkwOTYmcGFnZT0y"]
```
> ISSUE-516: Fixes Bug introduced by myself on 1.5.0 and adds Configurable resumptionToken
